std = 'lua54'
max_line_length = 120

globals = {
  'AddEventHandler',
  'CancelEvent',
  'Citizen',
  'CreateThread',
  'GetConvar',
  'GetConvarInt',
  'GetCurrentResourceName',
  'GetEntityModel',
  'GetEntityType',
  'GetGameTimer',
  'GetInvokingResource',
  'GetPlayerEndpoint',
  'GetPlayerIdentifiers',
  'GetPlayerName',
  'GetPlayers',
  'GetResourceState',
  'NetworkGetEntityFromNetworkId',
  'NetworkGetEntityOwner',
  'IsDuplicityVersion',
  'MySQL',
  'Player',
  'RegisterCommand',
  'DropPlayer',
  'GetCurrentServerEndpoint',
  'GetResourceKvpString',
  'RegisterNetEvent',
  'SetResourceKvp',
  'TriggerClientEvent',
  'TriggerLatentServerEvent',
  'TriggerServerEvent',
  'RegisterNUICallback',
  'SendNUIMessage',
  'TriggerEvent',
  'SetHttpHandler',
  'Wait',
  'exports',
  'json',
  'lib',
  'locale',
  'source',
}
