return {
    version = 1,
    name = 'initial_schema',
    statements = {
        [[CREATE TABLE IF NOT EXISTS sac_server_installation (
            installation_id VARCHAR(40) PRIMARY KEY,
            secret_hash VARCHAR(255) NOT NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_players (
            id VARCHAR(40) PRIMARY KEY,
            display_name VARCHAR(128) NULL,
            risk_score DECIMAL(8,3) NOT NULL DEFAULT 0,
            first_seen_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            last_seen_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            INDEX idx_sac_players_last_seen (last_seen_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_player_identifiers (
            player_id VARCHAR(40) NOT NULL,
            identifier_type VARCHAR(32) NOT NULL,
            identifier_hash CHAR(64) NOT NULL,
            identifier_value VARBINARY(512) NULL,
            first_seen_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            last_seen_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            PRIMARY KEY (player_id, identifier_type, identifier_hash),
            INDEX idx_sac_identifiers_lookup (identifier_type, identifier_hash),
            CONSTRAINT fk_sac_identifiers_player FOREIGN KEY (player_id) REFERENCES sac_players(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_player_sessions (
            id VARCHAR(40) PRIMARY KEY,
            player_id VARCHAR(40) NOT NULL,
            server_source INT UNSIGNED NULL,
            endpoint_hash CHAR(64) NULL,
            connected_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            disconnected_at TIMESTAMP(3) NULL,
            disconnect_reason VARCHAR(512) NULL,
            INDEX idx_sac_sessions_player_time (player_id, connected_at),
            CONSTRAINT fk_sac_sessions_player FOREIGN KEY (player_id) REFERENCES sac_players(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_fingerprints (
            id VARCHAR(40) PRIMARY KEY,
            algorithm_version SMALLINT UNSIGNED NOT NULL,
            fingerprint_hash CHAR(64) NOT NULL,
            first_seen_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            last_seen_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            UNIQUE KEY uq_sac_fingerprint_version_hash (algorithm_version, fingerprint_hash)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_fingerprint_observations (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            fingerprint_id VARCHAR(40) NOT NULL,
            player_id VARCHAR(40) NOT NULL,
            session_id VARCHAR(40) NOT NULL,
            attributes_json JSON NOT NULL,
            observed_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            INDEX idx_sac_fp_obs_fingerprint_time (fingerprint_id, observed_at),
            INDEX idx_sac_fp_obs_player_time (player_id, observed_at),
            CONSTRAINT fk_sac_fp_obs_fingerprint FOREIGN KEY (fingerprint_id) REFERENCES sac_fingerprints(id),
            CONSTRAINT fk_sac_fp_obs_player FOREIGN KEY (player_id) REFERENCES sac_players(id),
            CONSTRAINT fk_sac_fp_obs_session FOREIGN KEY (session_id) REFERENCES sac_player_sessions(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_identity_links (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            source_player_id VARCHAR(40) NOT NULL,
            target_player_id VARCHAR(40) NOT NULL,
            score DECIMAL(8,3) NOT NULL,
            reasons_json JSON NOT NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            UNIQUE KEY uq_sac_identity_link (source_player_id, target_player_id),
            CONSTRAINT fk_sac_identity_source FOREIGN KEY (source_player_id) REFERENCES sac_players(id),
            CONSTRAINT fk_sac_identity_target FOREIGN KEY (target_player_id) REFERENCES sac_players(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_profiles (
            id VARCHAR(40) PRIMARY KEY,
            name VARCHAR(128) NOT NULL,
            description VARCHAR(512) NULL,
            active_version_id VARCHAR(40) NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            UNIQUE KEY uq_sac_profile_name (name)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_profile_versions (
            id VARCHAR(40) PRIMARY KEY,
            profile_id VARCHAR(40) NOT NULL,
            version INT UNSIGNED NOT NULL,
            config_json JSON NOT NULL,
            created_by VARCHAR(128) NOT NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            UNIQUE KEY uq_sac_profile_version (profile_id, version),
            CONSTRAINT fk_sac_profile_versions_profile FOREIGN KEY (profile_id) REFERENCES sac_profiles(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_detections (
            id VARCHAR(40) PRIMARY KEY,
            player_id VARCHAR(40) NOT NULL,
            session_id VARCHAR(40) NULL,
            profile_version_id VARCHAR(40) NULL,
            rule_key VARCHAR(128) NOT NULL,
            category VARCHAR(64) NOT NULL,
            severity TINYINT UNSIGNED NOT NULL,
            confidence DECIMAL(5,4) NOT NULL,
            status VARCHAR(32) NOT NULL DEFAULT 'open',
            measured_json JSON NOT NULL,
            occurred_at TIMESTAMP(3) NOT NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            INDEX idx_sac_detections_player_time (player_id, occurred_at),
            INDEX idx_sac_detections_rule_time (rule_key, occurred_at),
            CONSTRAINT fk_sac_detections_player FOREIGN KEY (player_id) REFERENCES sac_players(id),
            CONSTRAINT fk_sac_detections_session FOREIGN KEY (session_id) REFERENCES sac_player_sessions(id),
            CONSTRAINT fk_sac_detections_profile_version FOREIGN KEY (profile_version_id) REFERENCES sac_profile_versions(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_detection_evidence (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            detection_id VARCHAR(40) NOT NULL,
            evidence_type VARCHAR(64) NOT NULL,
            reference_id VARCHAR(40) NULL,
            payload_json JSON NOT NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            INDEX idx_sac_evidence_detection (detection_id),
            CONSTRAINT fk_sac_evidence_detection FOREIGN KEY (detection_id) REFERENCES sac_detections(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_cases (
            id VARCHAR(40) PRIMARY KEY,
            player_id VARCHAR(40) NOT NULL,
            status VARCHAR(32) NOT NULL DEFAULT 'open',
            priority TINYINT UNSIGNED NOT NULL DEFAULT 0,
            title VARCHAR(255) NOT NULL,
            assigned_to VARCHAR(128) NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            updated_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
            INDEX idx_sac_cases_status_updated (status, updated_at),
            CONSTRAINT fk_sac_cases_player FOREIGN KEY (player_id) REFERENCES sac_players(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_case_events (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            case_id VARCHAR(40) NOT NULL,
            action_id VARCHAR(40) NULL,
            event_type VARCHAR(64) NOT NULL,
            actor VARCHAR(128) NOT NULL,
            body_json JSON NOT NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            INDEX idx_sac_case_events_case_time (case_id, created_at),
            CONSTRAINT fk_sac_case_events_case FOREIGN KEY (case_id) REFERENCES sac_cases(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_actions (
            id VARCHAR(40) PRIMARY KEY,
            correlation_id VARCHAR(40) NOT NULL,
            actor_type VARCHAR(32) NOT NULL,
            actor_id VARCHAR(128) NULL,
            action_type VARCHAR(64) NOT NULL,
            target_type VARCHAR(32) NULL,
            target_id VARCHAR(128) NULL,
            reason VARCHAR(1024) NULL,
            metadata_json JSON NOT NULL,
            profile_version_id VARCHAR(40) NULL,
            origin VARCHAR(64) NOT NULL,
            reverses_action_id VARCHAR(40) NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            INDEX idx_sac_actions_correlation (correlation_id),
            INDEX idx_sac_actions_target_time (target_type, target_id, created_at),
            CONSTRAINT fk_sac_actions_reversal FOREIGN KEY (reverses_action_id) REFERENCES sac_actions(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_bans (
            id VARCHAR(40) PRIMARY KEY,
            player_id VARCHAR(40) NOT NULL,
            action_id VARCHAR(40) NOT NULL,
            reason VARCHAR(1024) NOT NULL,
            expires_at TIMESTAMP(3) NULL,
            revoked_by_action_id VARCHAR(40) NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            INDEX idx_sac_bans_player_active (player_id, expires_at),
            CONSTRAINT fk_sac_bans_player FOREIGN KEY (player_id) REFERENCES sac_players(id),
            CONSTRAINT fk_sac_bans_action FOREIGN KEY (action_id) REFERENCES sac_actions(id),
            CONSTRAINT fk_sac_bans_revocation FOREIGN KEY (revoked_by_action_id) REFERENCES sac_actions(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_exceptions (
            id VARCHAR(40) PRIMARY KEY,
            scope_type VARCHAR(32) NOT NULL,
            scope_value VARCHAR(255) NOT NULL,
            effect VARCHAR(32) NOT NULL,
            reason VARCHAR(1024) NOT NULL,
            created_by VARCHAR(128) NOT NULL,
            expires_at TIMESTAMP(3) NULL,
            revoked_by_action_id VARCHAR(40) NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            INDEX idx_sac_exceptions_scope (scope_type, scope_value, expires_at),
            CONSTRAINT fk_sac_exceptions_revocation FOREIGN KEY (revoked_by_action_id) REFERENCES sac_actions(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_captures (
            id VARCHAR(40) PRIMARY KEY,
            player_id VARCHAR(40) NOT NULL,
            detection_id VARCHAR(40) NULL,
            case_id VARCHAR(40) NULL,
            storage_key VARCHAR(512) NOT NULL,
            media_type VARCHAR(64) NOT NULL,
            byte_size INT UNSIGNED NOT NULL,
            sha256 CHAR(64) NOT NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            INDEX idx_sac_captures_player_time (player_id, created_at),
            CONSTRAINT fk_sac_captures_player FOREIGN KEY (player_id) REFERENCES sac_players(id),
            CONSTRAINT fk_sac_captures_detection FOREIGN KEY (detection_id) REFERENCES sac_detections(id),
            CONSTRAINT fk_sac_captures_case FOREIGN KEY (case_id) REFERENCES sac_cases(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_ocr_results (
            id VARCHAR(40) PRIMARY KEY,
            capture_id VARCHAR(40) NOT NULL,
            rule_version VARCHAR(40) NOT NULL,
            raw_text MEDIUMTEXT NOT NULL,
            matches_json JSON NOT NULL,
            confidence DECIMAL(5,4) NULL,
            duration_ms INT UNSIGNED NOT NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            INDEX idx_sac_ocr_capture (capture_id),
            CONSTRAINT fk_sac_ocr_capture FOREIGN KEY (capture_id) REFERENCES sac_captures(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_watch_sessions (
            id VARCHAR(40) PRIMARY KEY,
            player_id VARCHAR(40) NOT NULL,
            started_by VARCHAR(128) NOT NULL,
            status VARCHAR(32) NOT NULL,
            started_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            ended_at TIMESTAMP(3) NULL,
            metadata_json JSON NOT NULL,
            INDEX idx_sac_watch_player_time (player_id, started_at),
            CONSTRAINT fk_sac_watch_player FOREIGN KEY (player_id) REFERENCES sac_players(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_api_keys (
            id VARCHAR(40) PRIMARY KEY,
            name VARCHAR(128) NOT NULL,
            key_prefix VARCHAR(24) NOT NULL,
            secret_hash VARCHAR(255) NOT NULL,
            scopes_json JSON NOT NULL,
            restrictions_json JSON NOT NULL,
            expires_at TIMESTAMP(3) NULL,
            last_used_at TIMESTAMP(3) NULL,
            revoked_at TIMESTAMP(3) NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            UNIQUE KEY uq_sac_api_key_prefix (key_prefix)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_staff_roles (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            role_key VARCHAR(64) NOT NULL,
            name VARCHAR(128) NOT NULL,
            permissions_json JSON NOT NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            UNIQUE KEY uq_sac_staff_role_key (role_key)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_staff_bindings (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            role_id BIGINT UNSIGNED NOT NULL,
            subject_type VARCHAR(32) NOT NULL,
            subject_value VARCHAR(255) NOT NULL,
            created_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            UNIQUE KEY uq_sac_staff_binding (role_id, subject_type, subject_value),
            CONSTRAINT fk_sac_staff_binding_role FOREIGN KEY (role_id) REFERENCES sac_staff_roles(id)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
        [[CREATE TABLE IF NOT EXISTS sac_outbox (
            id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
            topic VARCHAR(128) NOT NULL,
            aggregate_id VARCHAR(40) NULL,
            payload_json JSON NOT NULL,
            attempt_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
            available_at TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
            delivered_at TIMESTAMP(3) NULL,
            last_error VARCHAR(1024) NULL,
            INDEX idx_sac_outbox_delivery (delivered_at, available_at)
        ) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci]],
    },
}
