return {
    key = 'balanced_roleplay',
    name = 'Balanced roleplay',
    version = 1,
    correlationWindowMs = 60000,
    caseThreshold = 140,
    temporaryBanHours = 1,
    enforcement = {
        warn = 160,
        restrict = 220,
        kick = 300,
        temporaryBan = 450,
        permanentBan = 700,
    },
    -- Any rule entry may set `announce = true/false` to print (or silence) its accepted detections in the
    -- server console, overriding the rule's default.
    rules = {
        ['integrity.heartbeat_failure'] = {
            enabled = true,
            mode = 'log',
            severityMultiplier = 1.0,
            minimumConfidence = 1.0,
        },
        ['integrity.resource_inventory_drift'] = {
            enabled = true,
            mode = 'log',
            severityMultiplier = 1.0,
            minimumConfidence = 0.70,
        },
        ['network.entity_rate'] = {
            enabled = true,
            mode = 'cancel',
            severityMultiplier = 1.0,
            minimumConfidence = 0.80,
        },
        ['network.entity_model'] = {
            enabled = true,
            mode = 'cancel',
            severityMultiplier = 1.0,
            minimumConfidence = 0.95,
        },
        ['network.explosion_rate'] = {
            enabled = true,
            mode = 'cancel',
            severityMultiplier = 1.0,
            minimumConfidence = 0.85,
        },
        ['network.explosion_abnormal'] = {
            enabled = true,
            mode = 'cancel',
            severityMultiplier = 1.0,
            minimumConfidence = 0.95,
        },
        ['network.projectile_abnormal'] = {
            enabled = true,
            mode = 'cancel',
            severityMultiplier = 1.0,
            minimumConfidence = 0.85,
        },
        ['network.particle_abnormal'] = {
            enabled = true,
            mode = 'cancel',
            severityMultiplier = 1.0,
            minimumConfidence = 0.80,
        },
        ['network.event_rate'] = {
            enabled = true,
            mode = 'cancel',
            severityMultiplier = 1.0,
            minimumConfidence = 0.90,
        },
        ['evidence.ocr_match'] = {
            enabled = true,
            mode = 'log',
            severityMultiplier = 1.0,
            minimumConfidence = 0.50,
        },
        ['identity.ban_evasion'] = {
            enabled = true,
            mode = 'log',
            severityMultiplier = 1.0,
            minimumConfidence = 0.50,
        },
        ['integration.protected_event'] = {
            enabled = true,
            mode = 'cancel',
            severityMultiplier = 1.0,
            minimumConfidence = 0.95,
        },
        ['integrity.nui_devtools'] = { enabled = true, mode = 'temporary_ban', severityMultiplier = 1.0, minimumConfidence = 0.60 },
        ['integrity.nui_devtools_progress'] = { enabled = true, mode = 'log', severityMultiplier = 1.0, minimumConfidence = 0.40 },
        ['movement.teleport'] = { enabled = true, mode = 'log', severityMultiplier = 1.0, minimumConfidence = 0.60 },
        ['movement.noclip'] = { enabled = true, mode = 'log', severityMultiplier = 1.0, minimumConfidence = 0.50 },
        ['movement.speed'] = { enabled = true, mode = 'log', severityMultiplier = 1.0, minimumConfidence = 0.50 },
        ['movement.super_jump'] = { enabled = true, mode = 'log', severityMultiplier = 1.0, minimumConfidence = 0.55 },
        ['movement.freecam'] = { enabled = true, mode = 'log', severityMultiplier = 0.7, minimumConfidence = 0.40 },
        ['state.health'] = { enabled = true, mode = 'log', severityMultiplier = 0.7, minimumConfidence = 0.45 },
        ['state.visibility'] = { enabled = true, mode = 'log', severityMultiplier = 0.8, minimumConfidence = 0.50 },
        ['state.vision'] = { enabled = true, mode = 'log', severityMultiplier = 0.5, minimumConfidence = 0.40 },
        ['state.model'] = { enabled = true, mode = 'log', severityMultiplier = 0.4, minimumConfidence = 0.30 },
        ['state.godmode'] = { enabled = true, mode = 'log', severityMultiplier = 0.8, minimumConfidence = 0.55 },
        ['state.ragdoll_disabled'] = { enabled = true, mode = 'log', severityMultiplier = 0.4, minimumConfidence = 0.30 },
        ['combat.infinite_ammo'] = { enabled = true, mode = 'log', severityMultiplier = 0.8, minimumConfidence = 0.55 },
        ['vehicle.warp'] = { enabled = true, mode = 'log', severityMultiplier = 0.7, minimumConfidence = 0.50 },
        ['combat.fire_rate'] = { enabled = true, mode = 'log', severityMultiplier = 1.0, minimumConfidence = 0.60 },
        ['combat.weapon_blacklisted'] = { enabled = true, mode = 'cancel', severityMultiplier = 1.0, minimumConfidence = 0.90 },
        ['combat.weapon_not_owned'] = { enabled = true, mode = 'log', severityMultiplier = 1.0, minimumConfidence = 0.80 },
        ['combat.damage_excessive'] = { enabled = true, mode = 'cancel', severityMultiplier = 1.0, minimumConfidence = 0.90 },
        ['combat.damage_distance'] = { enabled = true, mode = 'cancel', severityMultiplier = 1.0, minimumConfidence = 0.85 },
        ['combat.damage_type_invalid'] = { enabled = true, mode = 'cancel', severityMultiplier = 1.0, minimumConfidence = 0.90 },
        ['combat.ammo_invalid'] = { enabled = true, mode = 'log', severityMultiplier = 0.8, minimumConfidence = 0.75 },
        ['combat.weapon_component_invalid'] = { enabled = true, mode = 'log', severityMultiplier = 0.8, minimumConfidence = 0.75 },
        ['combat.damage_without_shot'] = { enabled = true, mode = 'log', severityMultiplier = 0.5, minimumConfidence = 0.50 },
        ['combat.hit_rate'] = { enabled = true, mode = 'log', severityMultiplier = 0.7, minimumConfidence = 0.65 },
        ['combat.weapon_mismatch'] = { enabled = true, mode = 'log', severityMultiplier = 0.5, minimumConfidence = 0.50 },
        ['vehicle.speed'] = { enabled = true, mode = 'log', severityMultiplier = 0.7, minimumConfidence = 0.45 },
        ['vehicle.invulnerability'] = { enabled = true, mode = 'log', severityMultiplier = 0.8, minimumConfidence = 0.55 },
        ['vehicle.repair'] = { enabled = true, mode = 'log', severityMultiplier = 0.7, minimumConfidence = 0.45 },
        ['vehicle.handling_modified'] = { enabled = true, mode = 'log', severityMultiplier = 0.9, minimumConfidence = 0.60 },
        ['vehicle.boost'] = { enabled = true, mode = 'log', severityMultiplier = 0.8, minimumConfidence = 0.50 },
    },
}
